# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cea3c9c6268678ff08c42c783d0a3ac43d57c076cca8ffec59eb2ff04e5584ca69b87ac492b5bdddd66a21359ec43c315a600648194c687586d9dfb2018050c9

test:
  secret_key_base: 15f98c8d64120b4e751da4f7fdaaeefc7ea7419bf7fa1feb627d788cc8e736bec4ef6e871b40da4d1fdfbf5096e10b14af33d46fbfa00e301bed312e466e8b5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
